repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.19
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
          - --quiet
          - --no-hashes
          - --frozen
          - --no-header
          - --no-annotate
          - --no-default-groups
          - --output-file=requirements.txt
